server:
  port: 8083

#Database Config
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

#EurekaConfig
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka
